use super::Problem;

pub struct Problem002 {}

impl Problem for Problem002 {
    fn title(&self) -> &'static str {
        "Problem 2: Even Fibonacci numbers"
    }
    fn description(&self) -> &'static str {
        "Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:\n\
        \n\
        1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...\n\
        \n\
        By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms."
    }

    fn test(&self) {}

    fn answer(&self) {
        let mut prev = 1;
        let mut curr = 1;
        let mut sum = 0;

        while curr < 4000000 {
            if (curr % 2) == 0 {
                sum += curr;
            }

            let next = curr + prev;
            prev = curr;
            curr = next;
        }

        println!("[Answer] {}", sum);
    }
}
